import { test, expect } from '@playwright/test';

test.describe('Post Job', () => {


    test.beforeEach(async ({ page }) => {
        // Log in as employer
        await page.goto('http://localhost:3000/hr-login');
        await page.getByPlaceholder('Work email').fill(process.env.TESTUSER2_EMAIL!);
        await page.locator('input[type="password"]').fill(process.env.TESTUSER2_PASSWORD!);
        await page.getByRole('button', { name: /sign in as employer/i }).click();

        await expect(page).toHaveURL(/hr-dashboard/);

        // Go to Post Job page
        await page.getByRole('link', { name: 'Post Job', exact: true }).click();
        await expect(page).toHaveURL(/post-job/);
    });

    test('HR_JOB_001 - Verify job creation with valid data', async ({ page }) => {

    const jobTitle = 'Automated Test Engineer';

    await page.locator('label:has-text("Job title") input').fill(jobTitle);
    await page.locator('label:has-text("Company") input').fill('Worklance Test Corp');
    await page.locator('label:has-text("Location") input').fill('Bangalore, India');
    await page.locator('textarea').fill(
        'This is a test job description generated by automation.'
    );
    await page.locator('label:has-text("Min Monthly Salary") input').fill('60000');
    await page.locator('label:has-text("Max Monthly Salary") input').fill('90000');

    await page.getByRole('button', {
        name: /publish job/i
    }).click();

    // Verify success message
    await expect(
        page.getByText(/job posted successfully/i)
    ).toBeVisible();

    // Verify redirected to Manage Jobs
    await expect(page).toHaveURL(/manage-jobs/);

    // Verify a job card exists
    await expect(
    page.getByRole('article').first()
).toContainText(jobTitle);
});

    test('HR_JOB_002 - Verify Job Title mandatory field validation', async ({ page }) => {
        /*
        Test Scenario: Verify Job Title mandatory field validation
        Steps: Open Post Job page, Leave Job Title empty, Fill remaining fields, Click Publish
        Expected Result: Validation message displayed for Job Title
        */
        const titleInput = page.locator('label:has-text("Job title") input');
        await titleInput.fill(''); // Leave empty
        
        await page.locator('label:has-text("Company") input').fill('Worklance Test Corp');
        await page.locator('label:has-text("Location") input').fill('Bangalore, India');
        await page.locator('textarea').fill('This is a test job description.');
        await page.locator('label:has-text("Min Monthly Salary") input').fill('60000');
        await page.locator('label:has-text("Max Monthly Salary") input').fill('90000');

        await page.getByRole('button', { name: /publish job/i }).click();
        
        const isInvalid = await titleInput.evaluate((input: HTMLInputElement) => !input.checkValidity());
        expect(isInvalid).toBe(true);
    });

    test('HR_JOB_003 - Verify Description mandatory field validation', async ({ page }) => {
        /*
        Test Scenario: Verify Description mandatory field validation
        Steps: Open Post Job page, Leave Description empty, Fill remaining fields, Click Publish
        Expected Result: Validation message displayed for Description
        */
        await page.locator('label:has-text("Job title") input').fill('Automated Test Engineer');
        await page.locator('label:has-text("Company") input').fill('Worklance Test Corp');
        await page.locator('label:has-text("Location") input').fill('Bangalore, India');
        
        const descInput = page.locator('textarea');
        await descInput.fill(''); // Leave empty
        
        await page.locator('label:has-text("Min Monthly Salary") input').fill('60000');
        await page.locator('label:has-text("Max Monthly Salary") input').fill('90000');

        await page.getByRole('button', { name: /publish job/i }).click();

        const isInvalid = await descInput.evaluate((input: HTMLTextAreaElement) => !input.checkValidity());
        expect(isInvalid).toBe(true);
    });

    test('HR_JOB_004 - Verify salary range validation when Min Salary exceeds Max Salary', async ({ page }) => {
        /*
        Test Scenario: Verify salary range validation when Min Salary exceeds Max Salary
        Steps: Enter Min Salary greater than Max Salary, Click Publish
        Expected Result: Error message displayed
        */
        await page.locator('label:has-text("Job title") input').fill('Automated Test Engineer');
        await page.locator('label:has-text("Company") input').fill('Worklance Test Corp');
        await page.locator('label:has-text("Location") input').fill('Bangalore, India');
        await page.locator('textarea').fill('This is a test job description.');
        
        await page.locator('label:has-text("Min Monthly Salary") input').fill('100000');
        await page.locator('label:has-text("Max Monthly Salary") input').fill('50000'); // Min exceeds Max

        await page.getByRole('button', { name: /publish job/i }).click();

        await expect(page.getByText(/max salary cannot be less than min salary/i)).toBeVisible();
    });

    test('HR_JOB_005 - Verify salary range accepts equal values', async ({ page }) => {
        /*
        Test Scenario: Verify salary range accepts equal values
        Steps: Enter same value in Min Salary and Max Salary, Click Publish
        Expected Result: Job accepted according to business rules
        */
        await page.locator('label:has-text("Job title") input').fill('Automated Test Engineer');
        await page.locator('label:has-text("Company") input').fill('Worklance Test Corp');
        await page.locator('label:has-text("Location") input').fill('Bangalore, India');
        await page.locator('textarea').fill('This is a test job description.');
        
        await page.locator('label:has-text("Min Monthly Salary") input').fill('80000');
        await page.locator('label:has-text("Max Monthly Salary") input').fill('80000'); // Equal values

        await page.getByRole('button', { name: /publish job/i }).click();
        await expect(page).toHaveURL(/manage-jobs/);
    });

    test('HR_JOB_006 - Verify negative salary values are rejected', async ({ page }) => {

    const minSalaryInput = page.getByLabel(/min monthly salary/i);

    const maxSalaryInput = page.getByLabel(/max monthly salary/i);

    // Min salary validation
    await minSalaryInput.fill('-1000');

    await page.getByRole('button', {
        name: /publish job/i
    }).click();

    const minValidationMessage = await minSalaryInput.evaluate(
        (input: HTMLInputElement) => input.validationMessage
    );

    expect(minValidationMessage).toContain(
        'greater than or equal to 0'
    );

    // Max salary validation
    await maxSalaryInput.fill('-700000');

    await page.getByRole('button', {
        name: /publish job/i
    }).click();

    const maxValidationMessage = await maxSalaryInput.evaluate(
        (input: HTMLInputElement) => input.validationMessage
    );

    expect(maxValidationMessage).toContain(
        'greater than or equal to 0'
    );

});

    test('HR_JOB_007 - Verify salary field accepts only numeric values', async ({ page }) => {

    const minSalaryInput = page.locator(
        'label:has-text("Min Monthly Salary") input'
    );

    const maxSalaryInput = page.locator(
        'label:has-text("Max Monthly Salary") input'
    );

    await minSalaryInput.click();
    await page.keyboard.type('abc');

    await expect(minSalaryInput).toHaveValue('');

    await maxSalaryInput.click();
    await page.keyboard.type('xyz');

    await expect(maxSalaryInput).toHaveValue('');

});

    test('HR_JOB_008 - Verify Category selection functionality', async ({ page }) => {
        /*
        Test Scenario: Verify Category selection functionality
        Steps: Select Category from dropdown
        Expected Result: Selected Category saved successfully
        */
        const categorySelect = page.locator('label:has-text("Category") select');
        await categorySelect.selectOption('Design');
        await expect(categorySelect).toHaveValue('Design');
    });

    test('HR_JOB_009 - Verify Job Type selection functionality', async ({ page }) => {
        /*
        Test Scenario: Verify Job Type selection functionality
        Steps: Select Job Type from dropdown
        Expected Result: Selected Job Type saved successfully
        */
        const typeSelect = page.locator('label:has-text("Job type") select');
        await typeSelect.selectOption('Contract');
        await expect(typeSelect).toHaveValue('Contract');
    });

    test('HR_JOB_010 - Verify Work Mode selection functionality', async ({ page }) => {
        /*
        Test Scenario: Verify Work Mode selection functionality
        Steps: Select Work Mode option
        Expected Result: Selected Work Mode saved successfully
        */
        const modeSelect = page.locator('label:has-text("Work mode") select');
        await modeSelect.selectOption('Remote');
        await expect(modeSelect).toHaveValue('Remote');
    });

    test('HR_JOB_011 - Verify Shift selection functionality', async ({ page }) => {
        /*
        Test Scenario: Verify Shift selection functionality
        Steps: Select Shift option
        Expected Result: Selected Shift saved successfully
        */
        const shiftSelect = page.locator('label:has-text("Shift") select');
        await shiftSelect.selectOption('Night');
        await expect(shiftSelect).toHaveValue('Night');
    });

    test('HR_JOB_012 - Verify openings field validation for zero value', async ({ page }) => {
        /*
        Test Scenario: Verify openings field validation for zero value
        Steps: Enter 0 in openings field, Click Publish
        Expected Result: Validation message displayed
        */
        const openingsInput = page.locator('label:has-text("Openings") input');
        await openingsInput.fill('0');

        await page.getByRole('button', { name: /publish job/i }).click();
        const isInvalid = await openingsInput.evaluate((input: HTMLInputElement) => !input.checkValidity());
        expect(isInvalid).toBe(true);
    });

    test('HR_JOB_013 - Verify openings field accepts valid values', async ({ page }) => {
        /*
        Test Scenario: Verify openings field accepts valid values
        Steps: Enter valid openings count, Click Publish
        Expected Result: Input accepted successfully
        */
        const openingsInput = page.locator('label:has-text("Openings") input');
        await openingsInput.fill('5');
        await expect(openingsInput).toHaveValue('5');
    });

    test('HR_JOB_014 - Verify future closing date selection', async ({ page }) => {
        /*
        Test Scenario: Verify future closing date selection
        Steps: Select future closing date, Click Publish
        Expected Result: Future date accepted
        */
        const dateInput = page.locator('label:has-text("Closing date") input');
        const futureDate = new Date();
        futureDate.setDate(futureDate.getDate() + 10);
        const dateStr = futureDate.toISOString().split('T')[0];
        await dateInput.fill(dateStr);
        await expect(dateInput).toHaveValue(dateStr);
    });

    test('HR_JOB_015 - Verify past closing date validation', async ({ page }) => {
        /*
        Test Scenario: Verify past closing date validation
        Steps: Select past closing date, Click Publish
        Expected Result: Validation message displayed
        */
        const dateInput = page.locator('label:has-text("Closing date") input');
        const pastDate = new Date();
        pastDate.setDate(pastDate.getDate() - 5);
        const dateStr = pastDate.toISOString().split('T')[0];
        
        await dateInput.fill(dateStr);
        
        // Browser validation of min attribute prevents or flags this
        const isInvalid = await dateInput.evaluate((input: HTMLInputElement) => !input.checkValidity());
        expect(isInvalid).toBe(true);
    });

    test('HR_JOB_016 - Verify Urgent Hiring option functionality', async ({ page }) => {
        /*
        Test Scenario: Verify Urgent Hiring option functionality
        Steps: Enable Urgent Hiring option
        Expected Result: Urgent badge displayed
        */
        const checkbox = page.locator('label:has-text("Urgent hiring") input[type="checkbox"]');
        await checkbox.check();
        expect(await checkbox.isChecked()).toBe(true);
    });

    test('HR_JOB_017 - Verify Featured Listing option functionality', async ({ page }) => {
        /*
        Test Scenario: Verify Featured Listing option functionality
        Steps: Enable Featured Listing option
        Expected Result: Featured badge displayed
        */
        const checkbox = page.locator('label:has-text("Featured listing") input[type="checkbox"]');
        await checkbox.check();
        expect(await checkbox.isChecked()).toBe(true);
    });

    test('HR_JOB_018 - Verify Save as Draft functionality', async ({ page }) => {
        /*
        Test Scenario: Verify Save as Draft functionality
        Steps: Fill job details, Click Save as Draft
        Expected Result: Draft saved successfully
        */
        await page.locator('label:has-text("Job title") input').fill('Draft Job Title');
        await page.getByRole('button', { name: /save as draft/i }).click();

        await expect(page.getByText(/draft saved successfully/i)).toBeVisible();
    });

    test('HR_JOB_019 - Verify Publish Job functionality', async ({ page }) => {
        /*
        Test Scenario: Verify Publish Job functionality
        Steps: Fill all mandatory fields, Click Publish
        Expected Result: Success message displayed and job published
        */
        await page.locator('label:has-text("Job title") input').fill('Published Job Title');
        await page.locator('label:has-text("Company") input').fill('Worklance Test Corp');
        await page.locator('label:has-text("Location") input').fill('Bangalore, India');
        await page.locator('textarea').fill('This is a test job description.');
        await page.locator('label:has-text("Min Monthly Salary") input').fill('60000');
        await page.locator('label:has-text("Max Monthly Salary") input').fill('90000');
        
        await page.getByRole('button', { name: /publish job/i }).click();
        await expect(page).toHaveURL(/manage-jobs/);
    });

    test('HR_JOB_020 - Verify published job persists after refresh', async ({ page }) => {
        /*
        Test Scenario: Verify published job persists after refresh
        Steps: Publish job, Refresh page
        Expected Result: Published job remains available
        */
        await page.locator('label:has-text("Job title") input').fill('Persistent Job Title');
        await page.locator('label:has-text("Company") input').fill('Worklance Test Corp');
        await page.locator('label:has-text("Location") input').fill('Bangalore, India');
        await page.locator('textarea').fill('This is a test job description.');
        await page.locator('label:has-text("Min Monthly Salary") input').fill('60000');
        await page.locator('label:has-text("Max Monthly Salary") input').fill('90000');
        
        await Promise.all([
  page.waitForURL(/manage-jobs/),
  page.getByRole('button', {
    name: /publish job/i
  }).click()
]);

        await expect(
    page.getByRole('heading', {
        name: 'Persistent Job Title'
    }).first()
).toBeVisible();
    });
});
